import Header from './component/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Mulish } from 'next/font/google'


const mulist = Mulish({
  weight: ['300','400','500','600','700','800','900'],
  subsets:['latin'],
  display:'swap'
})

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className = {mulist.className}>
      <body >
        <Header/>
          {children}
      </body>
    </html>
  )
}
